In [2]:
#Question 1
import numpy

def arrays(arr):
    arr1 = numpy.array(arr,float)
    return arr1[-1::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [3]:
#Question 2
import numpy
def arrays(arr):
    return numpy.reshape(numpy.array(arr,int),(3,3))
arr = input().strip().split(' ')
result = arrays(arr)
print(result)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Question 3
import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten()) 


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [5]:
#Question 4
import numpy
n,m,p = map(int, input().split())
arr = numpy.array([input().split() for _ in range(n)], int)
arr1 = numpy.array([input().split() for _ in range(m)], int)
print(numpy.concatenate((arr,arr1), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [6]:
#Question 5
import numpy as np
shape = tuple(map(int,input().split()))
print(np.zeros(shape, dtype = np.int))
print(np.ones(shape, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [7]:
#Question 6
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
#Question 7
import numpy
n,m = map(int, input().split())
arr = numpy.array([input().split(' ') for _ in range(n)], int).reshape(n,m)
b = numpy.array([input().split(' ') for _ in range(n)], int).reshape(n,m)
print(arr+b)
print(arr-b)
print(arr*b)
print(arr//b)
print(arr%b)
print(arr**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [9]:
#Question 8
import numpy
numpy.set_printoptions(sign =' ')
arr = numpy.array(input().split(' '), float)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [10]:
#Question 9
import numpy as np
n,m = map(int, input().split())
arr = np.array([input().split() for _ in range(n)], int)
print(np.prod(np.sum(arr, axis=0)))

2 2
1 2
3 4
24


In [11]:
#Question 10
import numpy as np
n,m = map(int, input().split())
arr = np.array([input().split() for _ in range(n)],int)
print(np.max(np.min(arr, axis =1)))


4 2
2 5
3 7
1 3
4 0
3


In [12]:
#Question 11
import numpy as np
np.set_printoptions(sign=' ')
n,m = map(int,input().split())
arr = np.array([input().split() for _ in range(n)], int)
print(np.mean(arr, axis=1))
print(np.var(arr,axis=0))
print(round(np.std(arr),12))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [13]:
#Question 12
import numpy
n = int(input())
a= numpy.array([input().split() for _ in range(n)],int)
b= numpy.array([input().split() for _ in range(n)],int)
print(numpy.dot(a,b))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [14]:
#Question 13
import numpy
a = numpy.array([input().split()],int)
b = numpy.array([input().split()],int)
print(int(numpy.inner(a,b)))
print(numpy.outer(a,b))


0 1
2 3
3
[[0 0]
 [2 3]]


In [15]:
#Question 14
import numpy
print(numpy.polyval(list(map(float,input().split())),int(input())))


1.1 2 3
0
3.0


In [16]:
#Question 15
import numpy
n = int(input())
print(round(numpy.linalg.det(numpy.array([input().split() for _ in range(n)],float)),2))

2
1.1 1.1
1.1 1.1
0.0
